USE [master]
GO

/****** Object:  Database [FIS Alpine Skiing ]    Script Date: 11/20/2020 7:35:44 PM ******/
CREATE DATABASE [FIS Alpine Skiing ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FIS Alpine Skiing 1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.THUCANHLE\MSSQL\DATA\FIS Alpine Skiing 1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FIS Alpine Skiing 1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.THUCANHLE\MSSQL\DATA\FIS Alpine Skiing 1_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FIS Alpine Skiing ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FIS Alpine Skiing ] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET ARITHABORT OFF 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET  ENABLE_BROKER 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET RECOVERY FULL 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET  MULTI_USER 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FIS Alpine Skiing ] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FIS Alpine Skiing ] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FIS Alpine Skiing ] SET  READ_WRITE 
GO


